window:
  title: "JustBrowse"
  width: 515
  height: 620
  button_size: 25
  opacity_focus: 0.9
  opacity_fade: 0.3
  opacity_bg: 0.05

default:
  url_text: "https://github.com/allapse/JustBrowse"
  url_web: "https://allapse.github.io/allgivz/givez.html"
  status_expanded: False
  always_on_top: True
  animation_duration: 300
  status_rate: 2000

colors:
  text_sys: "170,170,170,0.5"
  text_app: "127,127,127,1.0"
  bg_sys: "127,127,127"
